name: Continuous Integration

on:
  push:
    branches:
      - next
      - feature/*
      - dependabot/*
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
          cache: yarn
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn ci
        name: Run integration tests
      - uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        name: Report code coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npx playwright install --with-deps chromium
        name: Install Chromium for Playwright
      - run: yarn test:e2e
        name: Run e2e tests
      - uses: 47ng/actions-slack-notify@main
        name: Notify on Slack
        if: always()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
